config/routes.rb
Rails
  .application
  .routes
  .draw do
    get 'robots', to: 'robots#index', as: 'robots'
    get 'robots/new', to: 'robots#new', as: 'new_robot'
    post 'robots', to: 'robots#create'
    get 'robots/:id', to: 'robots#show', as: 'robot'
    get 'robots/:id/edit', to: 'robots#edit', as: 'edit_robot'
    put 'robots/:id', to: 'robots#update'
    patch 'robots/:id', to: 'robots#update'
    delete 'robots/:id', to: 'robots#destroy'

    get 'checkout/success', to: 'transactions#success'
    get 'checkout/cancel', to: 'transactions#cancel'
    post 'transactions', to: 'transactions#create', as: 'transactions'

    get '/profile', to: 'users#show', as: 'user'
    get '/profile/managerobots', to: 'robots#manage', as: 'manage_robots'
    
    devise_for :users
    root 'home#index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/robot.rb
class Robot < ApplicationRecord
  # A robot can have one image attached. 
  has_one_attached :image
  
  # Validates that when creating a robot there must be a name and price which is greter then 0. Also that 
  # the image uploaded is of a certain file type. 
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

  # A robot belongs to 1 user 
  belongs_to :user, dependent: :destroy

  # A robot can have many belongs to many categories. which is connected via the Categories_Robots table  
  has_and_belongs_to_many :categories

  # a Robot can only be sold once so has one sale. Which gets recorded in the transactions. 
  has_one :sale, class_name: 'Transaction', foreign_key: :robot_id, dependent: :destroy

end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  
  # pull the specific robot from the database and sets it before a method is run. 
  before_action :set_robot, only: %i[show edit update destroy]
  
  # prompts for login if user not signed in
  before_action :authenticate_user!, except: %i[index]

  # ensure user has permission to change that robot.
  before_action :access_robot, :sold_robots, only: %i[edit update destroy]

  rescue_from RuntimeError, with: :unauthorised

  # Unathorised method to only allow users to edit their own robots
  def unauthorised
    flash[:notice] = 'Unauthorised operation. Please try another option '
    redirect_to robots_path
  end

  # Index page to list all robots that have not been sold yet.  
  def index
    @robots = Robot.where.missing(:sale).order(params[:sort])
  end

  # Initialise a new robot
  def new
    @robot = Robot.new
  end

  # Method to create robot 
  def create
    @robot = Robot.new(robot_params)
    if @robot.save
      flash[:notice] = 'Robot was successfully created'
      redirect_to robots_path
    else
      redirect_to new_robot_path,
      flash[:alert] = 'Error saving robot. Please try again'
    end
  end

  def show 
  end

  def edit 
  end

  # Method to update a specific robot
  def update
    if @robot.update(robot_params)
      flash[:notice] = 'Robot was successfully updated'
      redirect_to @robot
    else
      redirect_to @robot,
      flash[:alert] = 'Error updating robot. Please try again'
    end
  end

  # Destroys a specific 
  def destroy
    @robot.destroy
    flash[:notice] = 'Robot was successfully deleted'
    redirect_to robots_path
  end
  
  # Retrieves from database for a specific user the robots that they listed, have sold and purchased.  
  def manage
    @current_robots = current_user.robots.where.missing(:sale)
    @sold_robots = current_user.sold_robots
    @purchased_robots = current_user.purchased_robots
  end

  private

  # Calls the database based on the params to find a specifc robot.
  def set_robot
    begin
      @robot = Robot.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'That robot does not exist'
      redirect_to robots_path
    end
  end

  # Prevent any user besides the owner to edit a robot
  def access_robot
    raise 'unauthorised' if current_user != @robot.user 
  end

  def sold_robots
   if @robot.sold == true
     flash[:alert] = 'Robot has been sold and can no longer be updated'
     redirect_to robot_path(@robot)
   end
  end

  def robot_params
    params.require(:robot).permit(:name, :description, :price, :image, :user_id, category_ids: [])
  end
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/robots/_form.html.erb
<%= form_with(model: robot) do |form| %>
    <div class="field">
        <%= form.label :name %>: <br />
        <%= form.text_field :name, required: true, autofocus: true %>
    </div>
    <br>
    <div class="field">
        <%= form.label :description %>: <br />
        <%= form.text_area :description %>
    </div>
    <br>
    <div class="field">
        <%= form.label :price %>: <br />
        <%= form.number_field :price, min:0, required: true, autofocus: true %>
    </div>
 <br>
    <div class="field">
        <%= form.label :image %>: <br />
        <%= form.file_field :image, accept: 'image/png, image/jpg, image/jpeg' %>
        <%= image_tag(@robot.image) if @robot.image.attached?%>
    </div>
<br>
    <div class="field">
        <%= form.label :categories %> <br />
        <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
    </div>
<br>
    <div class="field">
        <%= form.text_field :user_id, id: :robot_user_id, value:current_user.id, type: :hidden%>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/robots/edit.html.erb
<h1>Edit your robot</h1>

<%= render "form", robot: @robot %>

app/views/robots/index.html.erb
<h1>Robot Listings </h1>

<table>
 <tr>
  <strong>Sort by: </strong><br />
   <th><%= link_to "Robot Name", :sort => "name"%> </th>
   <th><%= link_to "Price", :sort => "price"%> </th>
 </tr>
 </table>

<div class = "container" >
  <table class= "table" >
    <tr>  
      <th>Robot Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Seller</td>
    </tr>
    <% @robots.each do |robot| %>
    <tr>
        <td><%= link_to robot.name, robot_path(robot[:id]) %></td>
        <td>$<%= robot.price %></td>
        <td class="image" ><%= image_tag(robot.image) if robot.image.attached? %>  </td>
        <td><%= robot.user.username %></td>
    </tr>
    <% end %>  
  </table>
</div>

app/views/robots/manage.html.erb
<h1>Manage robots</h1>

<br />
<h2>Current Robots<h2>
<div class = "container" >
  <table class= "table" >
    <tr>  
      <th>Robot Name</th>
      <th>Price</th>
      <th>Image</th>
    </tr>
    <% @current_robots.each do |robot| %>
    <tr>
        <td><%= link_to robot.name, robot_path(robot[:id]) %></td>
        <td>$<%= robot.price %></td>
        <td><%= image_tag(robot.image) if robot.image.attached? %></td>
    </tr>
    <% end %>  
  </table>
</div>


<br />
<h2>Sold Robots<h2>
 <div class = "container" >
  <table class= "table" >
    <tr>  
      <th>Robot Name</th>
      <th>Price</th>
      <th>Image</th>
       <th>Buyer</th>
    </tr>
    <% @sold_robots.each do |robot| %>
    <tr>
        <td><%= link_to robot.name, robot_path(robot[:id]) %></td>
        <td>$<%= robot.price %></td>
        <td><%= image_tag(robot.image) if robot.image.attached? %></td>
        <td><%= robot.sale.buyer_id %></td>
    </tr>
    <% end %>  
  </table>
</div>

<br />
 <h2>Purchased Robots<h2>
 <div class = "container" >
  <table class= "table" >
    <tr>  
      <th>Robot Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Seller</td>
    </tr>
    <% @purchased_robots.each do |robot| %>
    <tr>
        <td><%= link_to robot.name, robot_path(robot[:id]) %></td>
        <td>$<%= robot.price %></td>
        <td><%= image_tag(robot.image) if robot.image.attached? %></td>
        <td><%= robot.user.username %></td>
    </tr>
    <% end %>  
  </table>
</div>

app/views/robots/new.html.erb
<h1>Sell a robot</h1>


<%= render "form", robot: @robot %>

app/views/robots/show.html.erb
<h1>Robots details</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @robot.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @robot.description %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @robot.price %>
</p>

<p>
  <strong>Categories:</strong>
  <% if @robot.category_ids.length != 0%>
    <% @robot.categories.each do |category| %>
      <%= category.name %>,
    <% end %>  
  <% else %>
    <strong>None</strong>
  <% end %>
</p>

<p>
  <strong>Image:</strong>
  <% if @robot.image.attached?%>
  <%= image_tag(@robot.image) %>
  <% else %>
    <%= image_tag "robot_image.png", alt: "default image", width: 150 %>
  <% end %>
</p>

<% if @robot.sold == true %>
  <strong>Robot Sold!</strong>
<% else %>
  <% if @robot.user != current_user %>
    <button type="button" id="checkout-button">Buy</button>
  <% end %>

  <% if @robot.user == current_user %>
    <%= link_to 'Edit', edit_robot_path(@robot) %> |
    <%= link_to 'Delete', @robot, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
<% end %>

<%= link_to 'Back', robots_path %>

<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
      fetch("/transactions", {
        method: "POST",
       headers: {
       'Content-Type': 'application/x-www-form-urlencoded'
     },
     body: "id=<%= @robot.id %>"
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });
  </script>

app/views/robots/update.html.erb
<h1>Robots#update</h1>
<p>Find me in app/views/robots/update.html.erb</p>