config/routes.rb
Rails
  .application
  .routes
  .draw do
    get 'robots', to: 'robots#index', as: 'robots'
    get 'robots/new', to: 'robots#new', as: 'new_robot'
    post 'robots', to: 'robots#create'
    get 'robots/:id', to: 'robots#show', as: 'robot'
    get 'robots/:id/edit', to: 'robots#edit', as: 'edit_robot'
    put 'robots/:id', to: 'robots#update'
    patch 'robots/:id', to: 'robots#update'
    delete 'robots/:id', to: 'robots#destroy'

    get 'checkout/success', to: 'transactions#success'
    get 'checkout/cancel', to: 'transactions#cancel'
    post 'transactions', to: 'transactions#create', as: 'transactions'

    get '/profile', to: 'users#show', as: 'user'
    get '/profile/managerobots', to: 'robots#manage', as: 'manage_robots'
    
    devise_for :users
    root 'home#index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "RobotBay", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Robot Listings/ Buy", robots_path, class: "nav-link"%>
        </li>  
      </ul>
       <ul class="navbar-nav  mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sell Robot", new_robot_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Manage Robots", manage_robots_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", user_path, class: "nav-link"%>
          </li>
          <li class="nav-item navbar-right">
            <%= link_to "Log Out", destroy_user_session_path, method: :DELETE, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
          </li>        
        <% end %>
     </ul>
    </div>
  </div>
</nav>

<!--        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
-->